/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.virca.api;

public class VirCAJavaApi {
  public static VirCADevice init() {
    long cPtr = VirCAJavaApiJNI.init();
    return (cPtr == 0) ? null : new VirCADevice(cPtr, false);
  }

}
