/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hu.sztaki.virca.api;

public class Vector3 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Vector3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VirCAJavaApiJNI.delete_Vector3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    VirCAJavaApiJNI.Vector3_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return VirCAJavaApiJNI.Vector3_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    VirCAJavaApiJNI.Vector3_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return VirCAJavaApiJNI.Vector3_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    VirCAJavaApiJNI.Vector3_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return VirCAJavaApiJNI.Vector3_z_get(swigCPtr, this);
  }

  public Vector3(float _x, float _y, float _z) {
    this(VirCAJavaApiJNI.new_Vector3(_x, _y, _z), true);
  }

}
