/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hu.sztaki.virca.api;

public class CyberDeviceAPIEventHandler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CyberDeviceAPIEventHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CyberDeviceAPIEventHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VirCAJavaApiJNI.delete_CyberDeviceAPIEventHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CyberDeviceAPIEventHandler() {
    this(VirCAJavaApiJNI.new_CyberDeviceAPIEventHandler(), true);
  }

  public void setAPI(SWIGTYPE_p_CyberDevice__CyberDeviceAPI API) {
    VirCAJavaApiJNI.CyberDeviceAPIEventHandler_setAPI(swigCPtr, this, SWIGTYPE_p_CyberDevice__CyberDeviceAPI.getCPtr(API));
  }

  public boolean onActivated() {
    return VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onActivated(swigCPtr, this);
  }

  public boolean onDeactivated() {
    return VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onDeactivated(swigCPtr, this);
  }

  public boolean onStartup() {
    return VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onStartup(swigCPtr, this);
  }

  public boolean onShutdown() {
    return VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onShutdown(swigCPtr, this);
  }

  public boolean onError() {
    return VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onError(swigCPtr, this);
  }

  public boolean onExecute() {
    return VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onExecute(swigCPtr, this);
  }

  public void onObjectSelected(SWIGTYPE_p_std__string name, SWIGTYPE_p_Ogre__Vector3 location) {
    VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onObjectSelected(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_Ogre__Vector3.getCPtr(location));
  }

  public void onSelfSelected(SWIGTYPE_p_std__string name, SWIGTYPE_p_Ogre__Vector3 location) {
    VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onSelfSelected(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_Ogre__Vector3.getCPtr(location));
  }

  public void onFunctionCalled(SWIGTYPE_p_std__string name, SWIGTYPE_p_std__string command) {
    VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onFunctionCalled(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_std__string.getCPtr(command));
  }

  public void onCollision(SWIGTYPE_p_std__string object1, SWIGTYPE_p_Ogre__Vector3 position1, SWIGTYPE_p_std__string object2, SWIGTYPE_p_Ogre__Vector3 position2) {
    VirCAJavaApiJNI.CyberDeviceAPIEventHandler_onCollision(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(object1), SWIGTYPE_p_Ogre__Vector3.getCPtr(position1), SWIGTYPE_p_std__string.getCPtr(object2), SWIGTYPE_p_Ogre__Vector3.getCPtr(position2));
  }

}
