/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hu.sztaki.virca.api;

public class VirCADevice extends CyberDeviceAPIEventHandler {
  private long swigCPtr;

  protected VirCADevice(long cPtr, boolean cMemoryOwn) {
    super(VirCAJavaApiJNI.VirCADevice_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirCADevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VirCAJavaApiJNI.delete_VirCADevice(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    VirCAJavaApiJNI.VirCADevice_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    VirCAJavaApiJNI.VirCADevice_change_ownership(this, swigCPtr, true);
  }

  public VirCADevice() {
    this(VirCAJavaApiJNI.new_VirCADevice(), true);
    VirCAJavaApiJNI.VirCADevice_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean onActivated() {
    return (getClass() == VirCADevice.class) ? VirCAJavaApiJNI.VirCADevice_onActivated(swigCPtr, this) : VirCAJavaApiJNI.VirCADevice_onActivatedSwigExplicitVirCADevice(swigCPtr, this);
  }

  public boolean onDeactivated() {
    return (getClass() == VirCADevice.class) ? VirCAJavaApiJNI.VirCADevice_onDeactivated(swigCPtr, this) : VirCAJavaApiJNI.VirCADevice_onDeactivatedSwigExplicitVirCADevice(swigCPtr, this);
  }

  public boolean onExecute() {
    return (getClass() == VirCADevice.class) ? VirCAJavaApiJNI.VirCADevice_onExecute(swigCPtr, this) : VirCAJavaApiJNI.VirCADevice_onExecuteSwigExplicitVirCADevice(swigCPtr, this);
  }

  public boolean onStartup() {
    return (getClass() == VirCADevice.class) ? VirCAJavaApiJNI.VirCADevice_onStartup(swigCPtr, this) : VirCAJavaApiJNI.VirCADevice_onStartupSwigExplicitVirCADevice(swigCPtr, this);
  }

  public void registerCyberDevice(String name, String meshName) {
    VirCAJavaApiJNI.VirCADevice_registerCyberDevice(swigCPtr, this, name, meshName);
  }

  public void setCyberDevicePosition(String name, Vector3 v) {
    VirCAJavaApiJNI.VirCADevice_setCyberDevicePosition(swigCPtr, this, name, Vector3.getCPtr(v), v);
  }

  public void print() {
    if (getClass() == VirCADevice.class) VirCAJavaApiJNI.VirCADevice_print(swigCPtr, this); else VirCAJavaApiJNI.VirCADevice_printSwigExplicitVirCADevice(swigCPtr, this);
  }

  public void onObjectSelected(SWIGTYPE_p_std__string name, SWIGTYPE_p_Ogre__Vector3 location) {
    if (getClass() == VirCADevice.class) VirCAJavaApiJNI.VirCADevice_onObjectSelected(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_Ogre__Vector3.getCPtr(location)); else VirCAJavaApiJNI.VirCADevice_onObjectSelectedSwigExplicitVirCADevice(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_Ogre__Vector3.getCPtr(location));
  }

  public Vector3 getCyberDevicePosition(String name) {
    return new Vector3(VirCAJavaApiJNI.VirCADevice_getCyberDevicePosition(swigCPtr, this, name), true);
  }

  public Vector3 getCameraPosition() {
    return new Vector3(VirCAJavaApiJNI.VirCADevice_getCameraPosition(swigCPtr, this), true);
  }

  public void onFunctionCalled(SWIGTYPE_p_std__string name, SWIGTYPE_p_std__string command) {
    if (getClass() == VirCADevice.class) VirCAJavaApiJNI.VirCADevice_onFunctionCalled(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_std__string.getCPtr(command)); else VirCAJavaApiJNI.VirCADevice_onFunctionCalledSwigExplicitVirCADevice(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_std__string.getCPtr(command));
  }

  public void onCollision(SWIGTYPE_p_std__string object1, SWIGTYPE_p_Ogre__Vector3 position1, SWIGTYPE_p_std__string object2, SWIGTYPE_p_Ogre__Vector3 position2) {
    if (getClass() == VirCADevice.class) VirCAJavaApiJNI.VirCADevice_onCollision(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(object1), SWIGTYPE_p_Ogre__Vector3.getCPtr(position1), SWIGTYPE_p_std__string.getCPtr(object2), SWIGTYPE_p_Ogre__Vector3.getCPtr(position2)); else VirCAJavaApiJNI.VirCADevice_onCollisionSwigExplicitVirCADevice(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(object1), SWIGTYPE_p_Ogre__Vector3.getCPtr(position1), SWIGTYPE_p_std__string.getCPtr(object2), SWIGTYPE_p_Ogre__Vector3.getCPtr(position2));
  }

}
